Dev/unit test (#1)
* WIP: add first unit test

* WIP: 集成 swaggo/swag

* WIP: update README

* WIP: 更新测试用例

* WIP: 补充 swagger docs

* 添加全局配置文件

* add chi middleware BasicAuth

* set package name to `github.com/twotwo/go-blueprint`

* add utils.DoHttpPost method

* mv docker-compose.yml -> deploy/docker-compose.yml

* add model package

* use go-swagger for spec server

* update go version to 1.23.5

* move origin main.go

* use oapi-codegen generate chi server code

* add -v in go test

* add skipbase for app/model/base_model_test.go

* Run go test with verbose output if previous test failed

diff --git a/.github/workflows/go-test.yml b/.github/workflows/go-test.yml
--- a/.github/workflows/go-test.yml
+++ b/.github/workflows/go-test.yml
@@ -1,18 +1,30 @@
 name: Go-test
 on: [push, pull_request]
 
+env:
+  CI: GITHUB # Set CI to GITHUB to enable CI-specific behavior in the code
+
 jobs:
   build:
     runs-on: ubuntu-latest
 
     steps:
       - uses: actions/checkout@v4
+
       - name: Setup Go
         uses: actions/setup-go@v4
         with:
-          go-version: '1.22.x'
+          go-version: "1.23.x"
 
       - name: Build
         run: go build -v ./...
-      - name: Test with the Go CLI
-        run: go test ./... 
+
+      - name: Run go test
+        id: test
+        run: go test ./... || echo "GO_TEST_FAILED=true" >> $GITHUB_ENV
+      - name: Test output verbose
+        if: env.GO_TEST_FAILED == 'true'
+        run: |
+          go clean -testcache
+          go test ./... -v
+          # go test ./... -v -tags skipbase
